const char *DOTA2_CFG_TEMPLATE =
"\"dota2-rpc-client Configuration\"\n"
"{\n"
"    \"uri\"               \"http://{{host}}:{{port}}/\"\n"
"    \"timeout\"           \"5.0\"\n"
"    \"buffer\"            \"0.1\"\n"
"    \"throttle\"          \"0.1\"\n"
"    \"heartbeat\"         \"30.0\"\n"
"    \"data\"\n"
"    {\n"
"        \"provider\"      \"1\"\n"
"        \"map\"           \"1\"\n"
"        \"player\"        \"1\"\n"
"        \"hero\"          \"1\"\n"
"        \"draft\"         \"1\"\n"
"        \"wearables\"     \"1\"\n"
"    }\n"
"    \"auth\"\n"
"    {\n"
"        \"token\"         \"518quwZuBDWr\"\n"
"    }\n"
"}";